### ISSUE TITLE
Next Hop/Forwarding Address Needs to be Included

### ISSUE THREAD

**Issue by riw777** [YangModels/yang#10]
The next hop/forwarding address is not included in this model, but should be.

**Comment by aashaikh** [comment]
in the current openconfig models, the set-next-hop action is augmented into the policy model by the routing protocol models.  If you look at bgp-policy.yang, it's in there.  

it could perhaps be considered a generic action included in the routing-policy model.

**Comment by einarnn** [comment]
Too old. Closing.
