### ISSUE TITLE
pyangbind and Cisco-IOS-XE-native

### ISSUE THREAD

**Issue by rgrueebler** [YangModels/yang#1003]
Hi everyone

I tried to generate some code with pyangbind. The yang model I used is the Cisco-IOS-XE-native. To generate the code I used the following command:
``
pyang --plugindir <path to virtualenv>/python3.9/site-packages/pyangbind/plugin -f pybind -o cisco_ios_xe_native.py <path to yang model>/Cisco-IOS-XE-native.yang -p yang-models/vendor/cisco/xe/1711/
``

Unfortunately, I get the following error>
``
INFO: encountered (<pyang.error.Position object at 0x7fcf0f085d80>, 'XPATH_NODE_NOT_FOUND2', ('Cisco-IOS-XE-native', 'native', 'Cisco-IOS-XE-interfaces'))
FATAL: pyangbind cannot build module that pyang has found errors with.
``

Is this an error in pyangbind or in the yang model itself?
I hope someone can help me with this.
Thanks
Remo

**Comment by einarnn** [comment]
This is actually a problem with pyang not being RFC-conformant. There is no problem with the model below.

**Comment by einarnn** [comment]
This is a pyang issue, not a model issue. Closing for now.
