### ISSUE TITLE
Error when importing instance date in ieee802-dot1q-bridge  ieee802-dot1q-sched

### ISSUE THREAD

**Issue by Lionelrt** [YangModels/yang#1020]
We setup sysrepo with  ieee802-dot1q-bridge,  ieee802-dot1q-sched, ietf-interfaces,...
When importing instance data with sysrepocfg we get libyang errors reported
Here is the interface instance data
<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces"
        xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">
    <interface>
      <name>interface1
      </name>
      <type>ianaift:ethernetCsmacd</type>
      <enabled>true</enabled>
    </interface>
  </interfaces>

and here are the libyang errors reported
sysrepocfg error: libyang: Identity "interface-type" has no derived identities, identityref with this base can never be instatiated.
sysrepocfg error: libyang: Identityref value is not derived from all its bases.
sysrepocfg error: libyang: Failed to resolve identityref "iana-if-type:bridge".
sysrepocfg error: libyang: Previous warning generated by XPath subexpression[0] "ietf-interfaces:type = 'iana-if-type:bridge'".
sysrepocfg error: libyang: Identity "interface-type" has no derived identities, identityref with this base can never be instatiated.
sysrepocfg error: libyang: Identityref value is not derived from all its bases.
sysrepocfg error: libyang: Failed to resolve identityref "iana-if-type:ethernetCsmacd".
sysrepocfg error: libyang: Previous warning generated by XPath subexpression[48] "ietf-interfaces:type ='iana-if-type:ethernetCsmacd'".
sysrepocfg error: libyang: Identity "interface-type" has no derived identities, identityref with this base can never be instatiated.
sysrepocfg error: libyang: Identityref value is not derived from all its bases.
sysrepocfg error: libyang: Failed to resolve identityref "iana-if-type:ieee8023adLag".
sysrepocfg error: libyang: Previous warning generated by XPath subexpression[103] "ietf-interfaces:type = 'iana-if-type:ieee8023adLag'".
sysrepocfg error: libyang: Identity "interface-type" has no derived identities, identityref with this base can never be instatiated.
sysrepocfg error: libyang: Identityref value is not derived from all its bases.
sysrepocfg error: libyang: Failed to resolve identityref "iana-if-type:ilan".
sysrepocfg error: libyang: Previous warning generated by XPath subexpression[157] "ietf-interfaces:type = 'iana-if-type:ilan'".
sysrepocfg error: libyang: Identity "interface-type" has no derived identities, identityref with this base can never be instatiated.
sysrepocfg error: libyang: Identityref value is not derived from all its bases.
sysrepocfg error: libyang: Failed to resolve identityref "iana-if-type:ethernetCsmacd".

Any hint is welcom on this issue

**Comment by samans** [comment]
Hi!  What this looks like is missing yang files that need to be available for the tooling.  The IANA module for if-types is not found in IETF github repository, but here: https://www.iana.org/assignments/iana-if-type/iana-if-type.xhtml or specifically here http://www.iana.org/assignments/yang-parameters/iana-if-type@2021-05-17.yang (updates when there are new if types).  If you are using ieee802-dot1q-sched, you are working with YANG in development.  The yang in the github found here https://github.com/YangModels/yang/tree/master/standard/ieee/draft does all validate with pyang and yanglint.  If you would like to discuss this on the phone send me a direct message.

**Comment by Lionelrt** [comment]
Issue fixed with using proper iani-if-type
