### ISSUE TITLE
Missing import in openconfig-platform-transceiver.yang

### ISSUE THREAD

**Issue by rgrueebler** [YangModels/yang#1023]
I everyone

I don't work with yang modules for a long time but I think that in the yang module
```
/vendor/cisco/xe/1731/openconfig-platform-transceiver.yang
```
there is a missing import at the beginning
```
import openconfig-platform-types { prefix oc-platform-types; }
```

Best regards
Remo

**Comment by einarnn** [comment]
@rgrueebler, yes, that version of the model is missing an import. The version Cisco publishes is unchanged from the one the OpenConfig group publishes. Cisco **does not modify models it does not own**. As you can see [here](https://github.com/openconfig/public/blob/8aff845fab8535ad9fcf301753394e91f5735f9b/release/models/platform/openconfig-platform-transceiver.yang) the `0.5.0` version published by OpenConfig is also missing this import.

This will not be changed on Cisco devices until they support a newer version of `openconfig-platform-transceiver`.

Closing as there is no issue for YangModels to resolve.
