### ISSUE TITLE
Store SNMP OID to YANG Xpath mapping data in this repository

### ISSUE THREAD

**Issue by miott** [YangModels/yang#1029]
Currently working on a Cisco project that will create tooling to map and verify SNMP OIDs to YANG model Xpaths.  The tooling output will be in the form of a CSV file.  Would like to store these files in a customer facing repository related to YANG files and this seems like the logical place.  Have not decided on a directory format yet.  Expect to have the first set of CSV files in about a month.  Eventually would like the tooling to automatically update the repository after an approval process.

**Comment by einarnn** [comment]
@miott Very open to this kind of idea, but also curious if this might align with the mission of the YANG Catalog? Have you had a discussion with the YANG Catalog maintainers?

Please feel free to reach out for a discussion when you are ready. We have automated approval flows worked out with YANG Catalog already, for example.

**Comment by miott** [comment]
YANG Catalog looks like a great place to feed this metadata to.
- MIB
- YANG module
- OID to Xpath mapping
I would guess this could take search, backend, and maybe UI contributions.  Are you the man to talk to about the flow?  I would definitely contribute.

**Comment by einarnn** [comment]
@miott, I’ll contact you directly about this.

**Comment by miott** [comment]
> @miott, I’ll contact you directly about this.

@einarnn Cisco SMEs will begin creating CSV files containing the OID to Xpath soon.  Ping me when you can talk.

**Comment by einarnn** [comment]
Discussion has happened elsewhere.

**Comment by divyark1488** [comment]
Hi @miott . Could you please give me information about what language, framework is used to achieve the conversion from OID to Xpath.

**Comment by miott** [comment]
> Hi @miott . Could you please give me information about what language, framework is used to achieve the conversion from OID to Xpath.

[YANG Suite](https://developer.cisco.com/yangsuite/) with yangsuite-coverage plugin which is available to public on pypi.org.
