### ISSUE TITLE
Add Arista YANG models

### ISSUE THREAD

**Issue by tedpelas** [YangModels/yang#1037]
Can we link Arista's YANG models as well?
https://github.com/aristanetworks/yang

Thank you

**Comment by einarnn** [comment]
Quite happy to have Arista’s models referenced here, say as a submodule, but it needs to be something Arista contribute and maintain, as do other vendors and standards groups. @tedpelas, if you know anyone in Arista that may want to arrange a contribution, please feel free to suggest they get in touch. 

Closing this issue.
