### ISSUE TITLE
联通相关数据删除

### ISSUE THREAD

**Issue by syclh** [YangModels/yang#1152]
您好，我是联通智慧安全敏感信息监测处置组的，您在Github平台是上传的信息涉及到联通内部敏感数据，希望您这边能将相关信息下线删除，URL如下：
https://github.com/YangModels/yang/blob/a1574848431529e1aabee76074342daa76ada129/experimental/ietf-extracted-YANG-modules/ietf-eth-service-oam%402021-07-10.yang

**Comment by einarnn** [comment]
Hi,

The content in this repository is just a reflection of an IETF draft. The content is automatically synchronized, and so I suggest that you work with the China Unicom co-author of the IETF draft to remove any sensitive content. Once that is removed it will be automatically removed from this repository.

Regards,

Einar Nilsen-Nygaard
