### ISSUE TITLE
联通相关数据删除

### ISSUE THREAD

**Issue by syclh** [YangModels/yang#1159]
您好，我是联通智慧安全敏感信息监测处置组的，您在Github平台是上传的信息涉及到联通内部敏感数据，希望您这边能将相关信息下线删除，URL如下：
https://github.com/YangModels/yang/blob/3284ae3c508cc653a9e99405ada7f5e11cc4d529/experimental/ietf-extracted-YANG-modules/ietf-supa-vpn%402015-03-24.yang

**Comment by einarnn** [comment]
Hi,

The content in this repository is just a reflection of an IETF draft. The content is automatically synchronized, and so I suggest that you work with the China Unicom co-author of the IETF draft to remove any sensitive content. Once that is removed it will be automatically removed from this repository.

Regards,

Einar Nilsen-Nygaard
