### ISSUE TITLE
ietf-l3vpn-ntw@2022-02-14.yang : Use of identities not proerly guarded by "if-feature" 

### ISSUE THREAD

**Issue by olofhagsand** [YangModels/yang#1165]
It seems several uses of identities in ietf-l3vpn-ntw@2022-02-14.yang is not properly guarded by "if-feature"
This includes on line 971:
```
                        leaf peer-mode {
                          type identityref {
                            base vpn-common:vxlan-peer-mode;
                          }
```
Which references the identity vxlan-peer-mode defined in ietf-vpn-common@2022-02-11.yang:
```
  identity vxlan-peer-mode {
    if-feature "vxlan";
    description
      "Base identity for VXLAN peer modes.";
  }
```
Which means ietf-l3vpn-ntw@2022-02-14.yang should probably use `if-feature "vpn-comon:vxlan"` at or around the definition of peer-mode.

This also applies to lack of i`f-feature "vpn-common:isis"` on line 2171:
```
                      leaf level {
                        type identityref {
                          base vpn-common:isis-level;
                        }
```

**Comment by einarnn** [comment]
@olofhagsand, these models are automatically added to this repo by trawling through the RFCs. To effect a change in these models it would be best to work through the relevant IETF WG that published the model.
