### ISSUE TITLE
commit 3db9bdb84cee02a1a2 went to wrong repo

### ISSUE THREAD

**Issue by abierman** [YangModels/yang#118]
I messed up somehow.
Thought I was committing to abierman/yang-ab1 but it went to the real repo instead.

Changes should be safe.

   moved ietf-restconf.yang from DRAFT to RFC
  moved ietf-restconf-monitoring.yang from DRAFT to RFC
  update modules with versions from RFC 8040

**Comment by tnadeau** [comment]
Please make sure none of the Travis CI tests break.

	—Tom
