### ISSUE TITLE
Missing iana-if-type import in ietf-interfaces?

### ISSUE THREAD

**Issue by jean-christophe-manciot** [YangModels/yang#1184]
@einarnn 
Interface types defined by iana-if-type YANG module are used by some network devices supporting ietf-interfaces, such as Cisco IOS-XE.
- why doesn't ietf-interfaces (all revisions) import iana-if-type?
- or is this a misuse on Cisco side?
- For instance, openconfig-if-ethernet does import it.

**Comment by einarnn** [comment]
@jean-christophe-manciot , sorry for delay in reply.

> - why doesn't ietf-interfaces (all revisions) import iana-if-type?

The IETF-defined `ietf-interfaces` model itself does not import `iana-if-type` because it doesn't need it and it would be an unnecessary import. `ietf-interfaces` defines and uses the **base** identity `interface-type` (see [here](https://github.com/YangModels/yang/blob/main/standard/ietf/RFC/ietf-interfaces%402018-02-20.yang#L68-L72)).

> - or is this a misuse on Cisco side?

No, Cisco tries not to modify the YANG models coming from other bodies that our devices publish use of.

> - For instance, openconfig-if-ethernet does import it.

This is because `openconfig-if-ethernet` needs to use specific interface types. In the case of  see [this reference](https://github.com/openconfig/public/blob/master/release/models/interfaces/openconfig-if-ethernet.yang#L667). In the case of Cisco models, see [here](https://github.com/YangModels/yang/blob/main/vendor/cisco/xe/1771/cisco-ethernet.yang#L76).

Thus the way the models do or do not import `iana-if-type.yang` is completely consistent with minimizing unnecessary imports and also correctly specifying the YANG files.

Historically, I believe that interface types in pre-RFC versions of `ietf-interfaces` were actually defined in `ietf-interfaces`, but the derived definitions were moved into a separate module to allow them to evolve independently from `ietf-interfaces`, which makes a lot of sense.

**Comment by jean-christophe-manciot** [comment]
@einarnn 
Then, what do you make of that type of response from an IOS-XE 17.6.1a?:
```
<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces"><interface><name>GigabitEthernet1</name><type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type><enabled>true</enabled><ipv4 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/><ipv6 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/></interface><interface><name>GigabitEthernet10</name><type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type><enabled>true</enabled><ipv4 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/><ipv6 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/></interface><interface><name>GigabitEthernet11</name><type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type><enabled>true</enabled><ipv4 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/><ipv6 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/></interface><interface><name>GigabitEthernet12</name><type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type><enabled>true</enabled><ipv4 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/><ipv6 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/></interface><interface><name>GigabitEthernet13</name><type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type><enabled>true</enabled><ipv4 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/><ipv6 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/></interface><interface><name>GigabitEthernet14</name><type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type><enabled>true</enabled><ipv4 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/><ipv6 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/></interface><interface><name>GigabitEthernet15</name><type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type><enabled>true</enabled><ipv4 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/><ipv6 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/></interface><interface><name>GigabitEthernet16</name><type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type><enabled>true</enabled><ipv4 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/><ipv6 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/></interface><interface><name>GigabitEthernet17</name><type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type><enabled>true</enabled><ipv4 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/><ipv6 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/></interface><interface><name>GigabitEthernet18</name><type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type><enabled>true</enabled><ipv4 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/><ipv6 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/></interface><interface><name>GigabitEthernet19</name><type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type><enabled>true</enabled><ipv4 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/><ipv6 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/></interface><interface><name>GigabitEthernet2</name><type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type><enabled>true</enabled><ipv4 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/><ipv6 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/></interface><interface><name>GigabitEthernet20</name><type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type><enabled>true</enabled><ipv4 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/><ipv6 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/></interface><interface><name>GigabitEthernet21</name><type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type><enabled>true</enabled><ipv4 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/><ipv6 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/></interface><interface><name>GigabitEthernet22</name><type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type><enabled>true</enabled><ipv4 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/><ipv6 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/></interface><interface><name>GigabitEthernet23</name><type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type><enabled>true</enabled><ipv4 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/><ipv6 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/></interface><interface><name>GigabitEthernet24</name><type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type><enabled>true</enabled><ipv4 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/><ipv6 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/></interface><interface><name>GigabitEthernet25</name><type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type><enabled>true</enabled><ipv4 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/><ipv6 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/></interface><interface><name>GigabitEthernet26</name><type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type><enabled>true</enabled><ipv4 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/><ipv6 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/></interface><interface><name>GigabitEthernet3</name><type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type><enabled>true</enabled><ipv4 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/><ipv6 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/></interface><interface><name>GigabitEthernet4</name><type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type><enabled>true</enabled><ipv4 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/><ipv6 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/></interface><interface><name>GigabitEthernet5</name><type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type><enabled>true</enabled><ipv4 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/><ipv6 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/></interface><interface><name>GigabitEthernet6</name><type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type><enabled>true</enabled><ipv4 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/><ipv6 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/></interface><interface><name>GigabitEthernet7</name><type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type><enabled>true</enabled><ipv4 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/><ipv6 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/></interface><interface><name>GigabitEthernet8</name><type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type><enabled>true</enabled><ipv4 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/><ipv6 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/></interface><interface><name>GigabitEthernet9</name><type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type><enabled>true</enabled><ipv4 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/><ipv6 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"/></interface></interfaces>...
```

**Comment by einarnn** [comment]
@jean-christophe-manciot, what toolchain are you using for xml --> json?

**Comment by jean-christophe-manciot** [comment]
@einarnn xsltproc

**Comment by einarnn** [comment]
@jean-christophe-manciot, I took a look at how the `jsonxsl` plugin for `pyang` works, and it seems that because of the approach taken you need to feed `pyang` all the models that your NETCONF agent can return content from for the queries you want to run. For example, on a Catalyst 8000v (I happened to have access to one) if I query for content from `ietf-interfaces`, then I need to create my stylesheet thus:

```
pyang -f jsonxsl ietf-interfaces.yang ietf-ip.yang iana-if-type.yang > ietf-interfaces.xsl
```

From just looking at `ietf-interfaces.yang` I can't tell that the other two are needed, so to correctly create a stylesheet for `ietf-interfaces` content I need to do a number off things:

- Download all models (can also get them from GitHub obviously!)
- Determine the top-level tags I care about
- Analyze all the models to:
    - Find the model(s) that contain the top level tags I care about (you may just know this, e.g. "I know I just care about `ietf-interfaces.yang`")
    - Find all the models that augment the model(s) that contain the top level tags I care about
- Analyze all the models identified so far to find any identityrefs declared and ensure that any model that extends those identityrefs is added to my list of models

Once you've done all that, you have the list of YANG models that you need to pass to `pyang -f jsonxsl ...` and a stylesheet will be correctly created that can process content.

This can all be automated using the underlying library from `pyang`. Not sure if you've used the underlying library before, but if you haven't there is sample code here that shows the basics of how to use it:

- https://github.com/CiscoDevNet/ncc/blob/master/ncc-get-all-schema
- https://github.com/CiscoDevNet/ncc/blob/master/ncc-get-schema

I realize this may seem onerous, but it is a consequence of how YANG has been designed to cater for extensibility.

**Comment by jean-christophe-manciot** [comment]
@einarnn 
I sincerely appreciate the time and effort you've put into this.

> For example, on a Catalyst 8000v (I happened to have access to one) if I query for content from `ietf-interfaces`, then I need to create my stylesheet thus:
> 
> ```
> pyang -f jsonxsl ietf-interfaces.yang ietf-ip.yang iana-if-type.yang > ietf-interfaces.xsl
> ```

On a CAT 8000v 17.6.1a, the command is much much longer than that:
- there are many more augmenting modules
- there are many more dependencies (imports and recursive imports) 
- you did not mention all deviations and features of all aforementioned modules either

> * Analyze all the models identified so far to find any identityrefs declared and ensure that any model that extends those identityrefs is added to my list of models

That's the key point of this discussion. Thanks.
I've taken an automated look at **all** the modules supported by the platform: there are a few modules which extend an identity defined in another module:
- ATM-TC-MIB@1998-10-19.yang
- cisco-routing-ext@2019-11-01.yang
- CISCO-SIP-UA-MIB@2004-02-19.yang
- CISCO-SMI@2012-08-29.yang
- cisco-xe-ietf-yang-push-ext@2020-04-27.yang
- cisco-xe-openconfig-acl-ext@2017-03-30.yang
- cisco-xe-openconfig-if-ethernet-ext@2017-10-30.yang
- DIFFSERV-MIB@2002-02-07.yang
- EtherLike-MIB@2003-09-19.yang
- iana-if-type@2014-05-08.yang
- ietf-diffserv-action@2015-04-07.yang
- ietf-ipv4-unicast-routing@2015-05-25.yang
- ietf-ipv6-unicast-routing@2015-05-25.yang
- ietf-ospf@2015-03-09.yang
- ietf-yang-push@2021-03-01.yang
- openconfig-aaa-radius@2017-09-18.yang
- openconfig-aaa-tacacs@2017-09-18.yang
- policy-types@2019-07-01.yang
- RMON-MIB@2000-05-11.yang
- SNMP-FRAMEWORK-MIB@2002-10-14.yang
- tailf-netconf-monitoring@2019-03-28.yang
- TOKENRING-MIB@1994-10-23.yang

> This can all be automated using the underlying library from `pyang`
- What do you mean by  ```all```?
- I don't see the link between pyang and your ncc scripts.

**Comment by einarnn** [comment]
> - What do you mean by  ```all```? ```pyang --format depend --depend-extension .yang --depend-from-submodules --depend-recurse``` does not include  any module which extends identities defined in passed module.

This command only detects dependencies expressed in the module you pass to the command. So, if you pass `iana-if-type.yang` it will identify `ietf-interfaces.yang`, but it won't detect anything the other way round.

> - I don't see the link between pyang and your ncc scripts other than making the YANG modules available to pyang.

I was referring to code like that highlighted by https://github.com/CiscoDevNet/ncc/blob/master/ncc-get-all-schema#L185-L198. This code shows how to parse a set of models into a repository and then query that repository. It's only a building block that then lets you write custom code to query the YANG tree. For example, you could take a model like `ietf-interfaces`, identify the identities declared in it and then look at all your other models to see if there are any identities using the ones from `ietf-interfaces` and hence the containing YANG modules.

The code to find any of these derived identities doesn't exist anywhere public that I am aware of.
