### ISSUE TITLE
Auto negotiate in Cisco-IOS-XE-interfaces-oper.yang

### ISSUE THREAD

**Issue by leopivat** [YangModels/yang#1228]
Hello,

I need to retrieve the information about the configured speed and duplex mode, so if the port is configured in auto mode, I need to know it's auto negotiate. For this I use the Cisco-IOS-XE-interface-common YANG model but I have an issue. When a port is configured in auto (speed auto and duplex auto), but nothing is connected behind, it shows me the correct value, auto-speed and auto-duplex. But when something is connected to this port, these values change to speed-1gb and full-duplex (for example). After reading the descriptions of these leafs, I understand it shows the value who has been negotiated. But for me the leaf "auto-negotiate" should be TRUE, instead of  FALSE because the port is still configured to auto for speed and duplex.

PS: I use actually IOS XE 16.02.06 and I try on a C9200, C9300 and C9401R

Thanks,

**Comment by einarnn** [comment]
@leopivat, all:

The various vendors who publish YANG models make the models available via this repo for developer convenience. However, this issue tracker is not a feed back to the vendors. Please use existing support mechanism the vendor provides!!
