### ISSUE TITLE
Incomplete Cisco-IOS-XE-crypto

### ISSUE THREAD

**Issue by xaviervalette** [YangModels/yang#1265]
Hello,

I hope you are all doing well,

## Context
I am trying to automate the deployment of SSL VPN on Catalyst 8000V Edge,

Unfortunately, I realize that the [Cisco-IOS-XE-crypto.yang](https://github.com/YangModels/yang/blob/main/vendor/cisco/xe/16101/Cisco-IOS-XE-crypto.yang) (1781) does not allow me to execute some of the configuration, such as:
```cli
crypto ssl authorization policy sslvpn-auth-policy
 client profile anyConnectProfile
 pool SSL_Client
 dns 8.8.8.8
 banner Welcome to the Cisco Catalyst 8000v SSL VPN
 route set access-list sslvpn-tunnel
```

## Question: Do you have any idea when this data will be accessible?

The exhaustive configuration is available [here](https://github.com/xaviervalette/AnyConnect-SSL-VPN-on-Catalyst-8000V-Edge/blob/main/c8kv1RunningConfig.txt).

**Comment by einarnn** [comment]
@xaviervalette, I'm afraid that this forum doesn't deal directly with the completeness or incompleteness of vendor models. Vendor representatives may read and respond, but I suggest that you approach your Cisco account team or partner with details of the missing content. They can help feed this through to the appropriate Cisco engineering team!
