### ISSUE TITLE
Cannot create YANG set if under score character is included anywhere in the name

### ISSUE THREAD

**Issue by davehouser1** [YangModels/yang#1337]
Trying to create a yang set named "cisco_xr_7_4_2" which uses the yang repo called "cisco_xr_7_4_2". I get the following error:

```
YANG Suite
YANG set name is not valid.
Make sure:

    It should have atleast one character.
    It should not start with any special character.
```

As you can see the name I choose follows the guidelines but yangsuite refuses to allow me to create with this name. 
Workaround: Do not include any `_` character in the name. This is then accepted as a suitable name by yangsuite

Recommendation: I can only assume there is a problem with a regex checking the name to make sure `_` is in the beginning of the name, but it is not working properly. I tested using other special characters, but only `_` seems to be the problem. Either fix whatever is restricting allowing me to create a name using `_` or include that "`_` cannot be used`" in the error output.

**Comment by einarnn** [comment]
@davehouser1, please raise this issue with:

https://github.com/CiscoDevNet/yangsuite

Closing here!
