### ISSUE TITLE
ietf-tcp-server@2022-10-19.yang is not a yang file

### ISSUE THREAD

**Issue by lllyfeng** [YangModels/yang#1350]
[yang](https://github.com/YangModels/yang)/[experimental](https://github.com/YangModels/yang/tree/main/experimental)/[ietf-extracted-YANG-modules](https://github.com/YangModels/yang/tree/main/experimental/ietf-extracted-YANG-modules)/ietf-tcp-server@2022-10-19.yang

**Comment by einarnn** [comment]
Fixed by #1349
