### ISSUE TITLE
Suggestion: Can the most current yang modules be the only included in `yang/standard/ietf/RFC`

### ISSUE THREAD

**Issue by manny-atx** [YangModels/yang#1360]
Hello,

I've been trying to reference these IETF yang modules to build models of my own, but it's hard to build a parser for the exact same module with different revisions in the title. 

Since the older modules are deprecated can they be moved to a `Deprecated` folder? So they don't cause conflicts when looking at the files? If they have been changed, git also allows for a historic view of commit changes to the module so there is no need to keep an old version of the file. 

Example:
```
ietf-l3vpn-svc@2017-01-27.yang
ietf-l3vpn-svc@2018-01-19.yang
ietf-l3vpn-svc.yang
```

The above might be easily distinguisable by a human, but how would you know which file to choose? Assuming your pointer is correct, the `ietf-l3vpn-svc.yang` will point on your computer to `ietf-l3vpn-svc@2018-01-19.yang`, but it just adds unneeded complexity. 

I feel like it would be a big improvement to only have `ietf-l3vpn-svc.yang` in the `yang/standard/ietf/RFC` directory especially since the modules themselves have an additional versioning and documentation inside of them. 

Thanks

**Comment by einarnn** [comment]
@manny-atx, the problem with your suggestion is that the older revisions of the models are not deprecated. They are just older. A netconf server may choose to support an older revision of a model if that is all that fits the capabilities it has. The rules for YANG backwards compatibility for IETF models mean that a client written to an older revision of a model will also be able to work with a server supporting the newer revision.

The link to the latest model revision is provided as a convenience. If you wish to only process the latest version of a model you can either filter for file names without the version extension or select the file with the most recent date. It is not appropriate to move the older revisions elsewhere as they are all still current and usable.

**Comment by bclaise** [comment]
@manny-atx , we are busy adding the following functionality in the yc.o search tool => "include draft". I am busy checking (as this functionality is brand new) but to me, it means that, without that one ticked, you would only have the RFCs.
