### ISSUE TITLE
Invalid Patterns In CISCO Yang Models

### ISSUE THREAD

**Issue by mmessa09** [YangModels/yang#138]
Apologies in advanced if I am incorrect. I am trying to use libyang in conjunction with this library of yang models and I an unable to parse several of the CISCO/XR/602 models files. 

For instance: Cisco-IOS-XR-types.yang

In troubleshooting this issue I've learned that libyang is complaining about the fact that the regex patterns  in this file contain un-escaped backslashes in double quotes, rather than escaping the the backslashes or enclosing the pattern in single quotes. 

I believe its the same issue documented here:

https://github.com/CESNET/libyang/issues/283

Note that I have the same issue with the yang model retrieved from the Cisco Router itself, so its clearly a disconnect rather than a typo. 

Thanks in advance for your help.

**Comment by einarnn** [comment]
We are aware of this issue and are working on resolving it for upcoming releases of XR. The issue may be patched locally by replacing " with ' in pattern statements.

Cheers,

Einar

**Comment by jean-christophe-manciot** [comment]
@einarnn  I've also discovered many issues when trying to convert all Cisco Yang modules to tree format with ```pyang -f tree```(pyang 1.7.1):
- **NX-OS** modules: invalid regular expressions 
- **IOS-XE** modules (1631): a few ```node ned::xxxxx is not found``` appeared.
- **IOX-XR** modules (534-600-601-602-611-612-613-621): many errors popped up when when the search path is set at ```cisco/xr```:
  + ```restriction require-instance not allowed for this base type``` ,
  + ```grouping "xxxxxx" not found in modulexxxx```, 
  + ```there is already a child node to "xxxxxx" at xxxx```,  
  + ```the list at "xxxxxxxxxx (at xr/600/xxxxxxxx)" needs at least one key because it is used as config```,
  + ```type "xxxxxxxx" not found in module xxxxx```.
  + ```node "xxxxxxxx" not found in module xxxxx```.
  + ```extension "xxxxxx" is not defined in module xxxxxxx```

Also, other errors appear when it is set at ```cisco/xr/<xr_version>```.

I'm not even listing the ton of warnings for unnecessary imports regarding modules across the board.

The whole log is available [here](https://github.com/YangModels/yang/files/919357/yang2tree-repositories-cisco-nos.log.txt)  when search_path="cisco/xr".

FYI, **all latest official openconfig Yang modules** (https://github.com/openconfig/public) pass the same conversion with flying colors, while some openconfig

**Comment by jean-christophe-manciot** [comment]
The whole log is available [here](https://github.com/YangModels/yang/files/919949/yang2tree-repositories-cisco-nos-version.log.txt) when **search_path="cisco/\<nos\>/\<nos_version\>"**.

**Comment by briantilburgs** [comment]
I have found some more issues with Backslashes..
in the following files mainly in Comments & Regex
/vendor/cisco/xe/1693/
Cisco-IOS-XE-aaa.yang
Cisco-IOS-XE-route-map.yang
Cisco-IOS-XE-rpc.yang 
openconfig-vlan-types.yang


I did correct them locally to use them for NSO.

Brian

**Comment by einarnn** [comment]
@briantilburgs, please raise the openconfig issues with the openconfig team, we don't modify their models when publishing. Will report Cisco models to appropriate team(s).

Cheers,

Einar

**Comment by einarnn** [comment]
Closing! Nothing for the owners of this repo to do.
