### ISSUE TITLE
Cisco Nexus 9000 BGP EVPN config using restconf openconfig model

### ISSUE THREAD

**Issue by umquresh** [YangModels/yang#1426]
Hi, 

I am unable to configure the following on a cisco nexus 9000 switch running NXOS version 10.2.5 using restconf API. I am trying to use the openconfig model. 

interface nve1
  no shutdown
  host-reachability protocol bgp
  advertise virtual-rmac
  source-interface loopback0
  member vni 900001 associate-vrf
  member vni 4010001
    suppress-arp
    mcast-group 239.0.0.1

evpn
  vni 4010001 l2
    rd auto
    route-target import auto
    route-target export auto
    
  fabric forwarding anycast-gateway-mac 0000.2222.3333
  
  
 API URL: https://10.x.x.x/restconf/data/openconfig-network-instance:network-instances
 
 
 Payload: 
 
 {
    "network-instance": [
        {
            "name": "default",           
            "fdb": {
                "config": {
                    "mac-aging-time": 1900,
                    "mac-learning": true,
                    "maximum-entries": 196000,
                    "anycast-gateway-mac": "00:00:22:22:33:33"
                }
            }
        }
    ]
}

Also for pim ssm range, I want to configure the following on the switch using openconfig model. 

ip pim ssm range 232.0.0.0/8

API Payload: 
{
    "network-instance": [
        {
            "name": "pim",
            "protocols": {
                "protocol": [
                    {
                        "identifier": "PIM",
                        "name": "pim",
                        "pim": {
                            "global": {
                                "ssm": {
                                    "ssm-ranges": "232.0.0.0/8"
                                }
                            }
                        }
                    }
                ]
            }
        }
    ]
}

**Comment by einarnn** [comment]
@umquresh, this repository is not really a clearing house for problems with the implementation vendors provide. May I suggest that in the case of issues with Cisco devices you contact Cisco TAC?

**Comment by einarnn** [comment]
@umquresh, this repository is not really a clearing house for problems with the implementation vendors provide. May I suggest that in the case of issues with Cisco devices you contact Cisco TAC?
