### ISSUE TITLE
Cisco platform version folder naming convention is not accurate

### ISSUE THREAD

**Issue by remingtonc** [YangModels/yang#173]
The [version folders](https://github.com/YangModels/yang/tree/master/vendor/cisco/xr) in the [platform folders](https://github.com/YangModels/yang/tree/master/vendor/cisco) under Cisco as a vendor do not match the actual version naming.

For example:
xr/621/ -> xr/6.2.1/

These little inconsistencies make it difficult to write parsing tools without an understanding of how to parse these folder names in to Cisco platform versions, which are unfortunately inconsistent in their versioning scheme as well.

Ideally, these folders should match the version names that they represent exactly.

**Comment by einarnn** [comment]
This may evolve over time.

**Comment by remingtonc** [comment]
@einarnn Could you provide some clarification to this point? If I submitted a pull request with naming conventions - would it be appropriate? Or is this evolving in a more difficult to reconcile manner that will need to come from you + friends?

**Comment by tnadeau** [comment]
I don’t know of any limitations but the wider community should have a day or two to comment in case they do care.

	—Tom

**Comment by einarnn** [comment]
I'm not really keen to rewrite history and change what we have already got committed and thus what the broader community may be using and referring. For example, we have lots of training and presentation material referring to the current paths, and thus changing them would be painful and quite possibly counter-productive. 

However, very happy to look at evolving the naming of directories moving forward to something that aligns more closely to what customers see in OS version output. But this is primarily and internal discussion.

@remingtonc, suggest you follow up with me and others.

**Comment by remingtonc** [comment]
This will be resolved with metadata going forward. This is present on several XR versions, [for example](https://github.com/YangModels/yang/blob/master/vendor/cisco/xr/611/platform-metadata.json).
