### ISSUE TITLE
Promiscuous Neighbor Support

### ISSUE THREAD

**Issue by riw777** [YangModels/yang#21]
In bgp-neighbors, there doesn't seem to be any way to account for promiscuous neighbor mode. This might be too implementation specific -- don't know -- but it might be worth considering making the address and peering AS either able to contain a "magic number" (though I hate magic numbers) to indicate "this is a promiscuous peering point," or to make it into a group of items, one of which could be a marker indicating there's no ip address and peering AS here because this is a promiscuous attachment point.

**Comment by einarnn** [comment]
Too old. Closing.
