### ISSUE TITLE
license model of Cisco Yang modules

### ISSUE THREAD

**Issue by AndreiChek** [YangModels/yang#350]
Hello @einarnn
Please advise for the license model of Cisco modules, or please advise whom to contact for this.

I've found the license model (Apache 2.0) for modules by Huawei and Juniper, but can't find it for Yang modules by Cisco.

Thank you,
Andrei

**Comment by tnadeau** [comment]
Einar should be able to answer that as he is managing that part of the repo.

	—Tom

**Comment by einarnn** [comment]
@AndreiChek, we’re in the process of clarifying this, and will hopefully update the repo soon.

Cheers,

Einar

**Comment by AndreiChek** [comment]
@einarnn 
Thank you Einar, will keep tracking 

Andrei
