### ISSUE TITLE
ask the reason of removing nc-notifications.yang&notifications.yang

### ISSUE THREAD

**Issue by fooljohnny** [YangModels/yang#353]
Hi, @mKunihiroIshiguro ,
i find these experimental yang files like notfications.yang/nc-notifications.yang were removed in this commit：
https://github.com/YangModels/yang/commit/f30999e18315cf39e6d8008b70211f5abb749607
if it have a newer yang to replace them?
or it will never have a notification1.0's yang file?
why they are being removed? I want to know about the backgroud.
thanks a lot!

sincerely yours.

**Comment by einarnn** [comment]
Too old. Closing.
