### ISSUE TITLE
Backslash use in some models (with a patch)

### ISSUE THREAD

**Issue by gkantsidis** [YangModels/yang#366]
A number of models seem to make incorrect use of the backslash in strings, which are typically either descriptions, or regular expressions (in pattern statements). Most frequently the problems are:
- Forgetting to escape the backslash operation in double quote strings. Often regular expressions are copied as is, without escaping the '\' character. 
- In a number of cases, multi-line strings use the backslash to terminate a line (similar to C code). This is not necessary, and it is also wrong.

I have fixed some of those problems (and few others) in the patches attached.
In retrospect, for the regular expressions, the better approach for many cases would have been to use single-quoted string; it was easier though to replace '\' with '\\'.

Many thanks for this repo. It is very useful!

-christos

[SomeFixes-MostlyWithBackslash.zip](https://github.com/YangModels/yang/files/1795548/SomeFixes-MostlyWithBackslash.zip)

**Comment by einarnn** [comment]
I think that vendors have mostly been fixing these issues. I can't ask vendors to retrospectively fixed already-released models, as the repo would then no longer mirror what the devices actually return.

Closing for now.

> Many thanks for this repo. It is very useful!

Thanks! :-)
