### ISSUE TITLE
Cisco-IOS-XR-aaa-locald-cfg problem with list key

### ISSUE THREAD

**Issue by rgaglian** [YangModels/yang#399]
Hi,

I will try to request the fix. Looks like "ordering-index" should not be a key.

Roque

admin@ncs> request devices device salerno sync-from
result false
info salerno: missing element: ordering-index in /ncs:devices/ncs:device[ncs:name='salerno']/ncs:config/aaa-lib-cfg:aaa/aaa-locald-cfg:usernames/aaa-locald-cfg:username
[ok][2018-06-06 17:35:21]
admin@ncs>

<usernames xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-aaa-locald-cfg">
    <username>
     <name>epnlab</name>
     <usergroup-under-usernames>
      <usergroup-under-username>
       <name>usergroup_read_only</name>
      </usergroup-under-username>
     </usergroup-under-usernames>
     <secret>
      <type>type5</type>
      <secret5>$1$UPDN$XV6e7Pn0HvmwaX1Ewsbea/</secret5>
     </secret>
    </username>
   </usernames>

**Comment by einarnn** [comment]
Roque,

Apologies for long delay in responding, but this is a deliberate change in newer versions of IOS-XR. Please ping me for a more detailed discussion if you have concerns.

Cheers,

Einar
