### ISSUE TITLE
Different line endings CR LF in the same file.

### ISSUE THREAD

**Issue by apmanol** [YangModels/yang#434]
Congratulation for the great repo.

Some files have different line endings, for example [ietf-microwave-radio-link](https://github.com/YangModels/yang/blob/master/experimental/ietf-extracted-YANG-modules/ietf-microwave-radio-link%402018-06-30.yang)
```bash 
$ cat -A experimental/ietf-extracted-YANG-modules/ietf-microwave-radio-link@2018-06-30.yang | more
module ietf-microwave-radio-link {^M$
  yang-version 1.1;^M$
  namespace "urn:ietf:params:xml:ns:yang:ietf-microwave-radio-link";^M$
  prefix mrl;^M$
$
  import ietf-yang-types {^M$
```

You can see that after `mrl;` there is a `^M` but in the new line exists only `$`

**Comment by einarnn** [comment]
Thanks! We're trying to broaden access to YANG models and make it easier to find and use them, so glad you find this resource useful!

Does this actually cause you any problems in your tooling? RFC 6020's ABNF grammar explicitly accepts CRLF and LF as the line break character sequence. See the bottom of page 163 , [Section 12 in the RFC](https://tools.ietf.org/html/rfc6020#section-12):

```
   line-break          = CRLF / LF
```

...and tools such as `pyang` have no issue accepting this format. If you tooling is having an issue with this, I do suggest that you talk to the tool provider/author and ask them to conform to the RFC in terms of accepting either line break sequence. This will improve tool robustness.

The specific file you identified is actually captured automatically from IETF drafts, and we do not change the format of the source files, we just extract the text from the draft, and so if the authors used CRLF, this will be reflected in what is in the git repository.

**Comment by tnadeau** [comment]
I had started to type a response yesterday, but got caught up in something else… anyways I was going to ask exactly that and what parser is being used?
One of the benefits of the Yang Repo here is that we have found lots of inconsistencies around the compilers and have worked to have
those fixed. If you can let us know specifically what you are using (with the output) we can help rectify that. 

—Tom

**Comment by apmanol** [comment]
Thanks for the replies.

To be honest there is no serious issue with the tooling, more with the editor which is nagging about this difference. Also in our git repo we enforce the same line ending, but it is also minor.

I thought that something have skipped from the extraction, that's why the issue was reporeted.

**Comment by apmanol** [comment]
Closing the issue since it seems that's a problem from the origin of the files.
