### ISSUE TITLE
IETF draft YANG extraction cronjob has stopped updating the repository

### ISSUE THREAD

**Issue by WilliamZSiemens** [YangModels/yang#438]
Hi,

I noticed recently that the daily cronjob for the IETF draft YANG module extraction from the draft IETF standards has stopped. I am specifically looking at the ietf-ptp.yang and the ietf-igmp-mld-snooping.yang. I believe these draft IETF modules have been updated recently. Was there an issue running the cronjob recently?

Thanks,
William Z

**Comment by tnadeau** [comment]
Can you try executing the code form the cron job locally and posting the output?

**Comment by WilliamZSiemens** [comment]
I am unfamiliar with how the cron job is done, I just notice the commit message about the cron job whenever the IETF draft YANG models get updated. Which script should I be looking at and trying to run?

**Comment by einarnn** [comment]
The team that runs the cronjob are currently working on the related software. @miroslavKovacPantheon may be able to comment?

**Comment by miroslavKovacPantheon** [comment]
Hi @WilliamZSiemens,

We were moving some jobs and one link got broken. I just fixed this so it should create a PR any time soon that will be merged right ietf modules when travis job will be succesfull.

Thank you for this issue.

**Comment by miroslavKovacPantheon** [comment]
@WilliamZSiemens PR was created -> https://github.com/YangModels/yang/pull/439 travis job is running

**Comment by miroslavKovacPantheon** [comment]
@WilliamZSiemens  ok it s done and merged. https://github.com/YangModels/yang/pull/439.. this job will again run every day as it did. 

Sorry for inconvenience

**Comment by WilliamZSiemens** [comment]
Thanks for the prompt fix for this. Both YANG models have been successfully updated.
