### ISSUE TITLE
Cisco IOS-XE porting route-map fails

### ISSUE THREAD

**Issue by briantilburgs** [YangModels/yang#455]
Hi All,

I'm a network engineer that found out how to program a Cisco ISR1000v/ Cisco ASR, and was very happy is worked..

Now it got broken because of an Upgrade.. I decided to go Your wy, the YANG way now, but that seems to be pretty hard.

Together with a TAC engineer I managed to get a lot of information from the devices and to configure interfaces. Now I'd like to configure some route-map (That I can already download with the GET) but that fails and I can't find out why.

Is there anybody that can help me to get the right format for my RESTCONF configuration?

WORKING:
curl -i -k -u cisco:cisco -X GET -H "Content-Type: application/yang-data+xml" https://10.110.1.213/restconf/data/ietf-interfaces:interfaces

curl -i -k -u cisco:cisco -X POST -H "Content-Type: application/yang-data+xml" -d '<interface><name>Loopback666</name><type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:softwareLoopback</type></interface>' https://10.110.1.213/restconf/data/ietf-interfaces:interfaces

curl -k -u cisco:cisco -H "Accept: application/yang-data+json" https://cisco:cisco@10.110.1.213/restconf/data/Cisco-IOS-XE-native:native/route-map="ZOM-ROUTE-toLEAF_RM"

How to configure this route-map?? POST/ PUT/ PATCH

Thanks,
Brian

**Comment by briantilburgs** [comment]
Wow, thanks!!! I'd create my first route map :-)

But i have a more important question: How did you come to this result.. for me it is still a bit magic and I'm looking for some strategy or standard steps to find out how to GET/ POS/ PUT etc.. to which URLs etc.

I'd find paying and created a tree for vieuwing in HTML, that helped me to find the URL that you sent me but How should I have found the JSON structure that you have sent me?

Thanks Very much,
Brian

**Comment by einarnn** [comment]
Knowing how to create the correct JSON or XML payload is a matter of:

- experience with the relevant RFCs (6020, 6241, 7951, 8040)
- experience with using the netconf and restconf interfaces on XE (I'm part of the Cisco engineering group)
- knowing how to work with relevant tools, like pyang

On that last bullet, the "shape" of the JSON payload is almost completely governed by the YANG data model, and we can use a tool like `pyang` (`pip install pyang`) to visualize that model:

```
$ pyang -f tree Cisco-IOS-XE-native.yang  Cisco-IOS-XE-route-map.yang --tree-path=/native/route-map --tree-depth=4
module: Cisco-IOS-XE-native
  +--rw native
     +--rw route-map* [name]
        +--rw name                                         string
        +--rw ios-route-map:route-map-seq* [ordering-seq]
        |  +--rw ios-route-map:ordering-seq    string
        |  +--rw ios-route-map:operation?      enumeration
        |  +--rw ios-route-map:sequence?       uint16
        |  +--rw ios-route-map:description?    string
        |  +--rw ios-route-map:set
        |  |     ...
        |  +--rw ios-route-map:match
        |        ...
        +--rw ios-route-map:route-map-without-order-seq* [seq_no]
           +--rw ios-route-map:seq_no         uint16
           +--rw ios-route-map:operation?     enumeration
           +--rw ios-route-map:description?   string
           +--rw ios-route-map:set
           |     ...
           +--rw ios-route-map:match
                 ...
```

From this, you should be able to see how the fields in the JSON payload correlate to the YANG model (where there is a `...` above, there is more content; the `--tree-depth` flag constrains how much is visible for readability in this, as the model is quite deep).

Also, while learning, constructing content through an interface you are familiar with, e.g. CLI, can also be instructive. It really depends what background you are coming from.

But, at the core, understanding how to work with YANG and how it maps onto the underlying netconf and restconf protocols is critical if you wish to create your own payloads for config.

Cheers,

Einar

**Comment by briantilburgs** [comment]
Thanks Einar, 

Again going forward and found the solution to the thing I need to build now, but even more curious about the working of the Yang model for building more scripts.

with this information I "tried and errorred" a bit more, took the depth to 8 and found some URLs.

first the solution:
```
curl -k -X "PATCH" "https://10.110.1.213/restconf/data/Cisco-IOS-XE-native:native/route-map" \
     -H 'Content-Type: application/yang-data+json' \
     -u 'cisco:cisco' \
     -d $'{
  "Cisco-IOS-XE-native:route-map": {
    "name": "TEST",
    "Cisco-IOS-XE-route-map:route-map-seq": [
      {
        "ordering-seq": "rule13",
        "set": {
          "tag": {"tag-val": 213},
          "metric": 234
        },
        "match": {
          "tag": {
            "tag_value": [101]
          }
        }
      }
    ]
  }
}'
```
I did just add the metric to your PATCH (above is the working one).

But before I came to the right solution, i Expected that I had to add the metric like:
```
         "set": {
           "tag": {"tag-val": 213},
           "metric": "values": [{ "value": 234}]
         },
```
Thats where I end up when I follow: 
`/ios:native/ios:route-map/ios-route-map:route-map-seq/ios-route-map:set/ios-route-map:metric/ios-route-map:values/ios-route-map:value`

(see attached file:
[Cisco-IOS-XE-route-map.html.zip](https://github.com/YangModels/yang/files/2414194/Cisco-IOS-XE-route-map.html.zip)

How should I know that the `/ios-route-map:values/` should be ignored and that the `ios-route-map:value` should be replaced by a "uint32"?

The YANG description for the route-map/set/metric is different than the route-map/set/tag

```
/ios:native/ios:route-map/ios-route-map:route-map-seq/ios-route-map:set/ios-route-map:tag/ios-route-map:tag-val
```
and 
```
/ios:native/ios:route-map/ios-route-map:route-map-seq/ios-route-map:set/ios-route-map:metric/ios-route-map:values/ios-route-map:value
```


Brian

**Comment by einarnn** [comment]
Brian,

You gave an example you said was working, but when I looked at it, I didn't think it would work on **IOS XE 16.9.1**, but then I looked back in the thread and saw that you didn't specify which version of XE you are using, so I checked back to the IOS XE 16.8.1 models:

```
$ pyang -f tree Cisco-IOS-XE-native.yang Cisco-IOS-XE-route-map.yang --tree-path=native/route-map/route-map-seq/set/metric
module: Cisco-IOS-XE-native
  +--rw native
     +--rw route-map* [name]
        +--rw ios-route-map:route-map-seq* [ordering-seq]
           +--rw ios-route-map:set
              +--rw ios-route-map:metric?   string
```

And, indeed, the metric value is simpler. However, technically thevalue is a string, and not an integer as your exanple encodes it, so I guess our JSON parser must be generous in what it accepts! ;-)

Specifically you asked:

> How should I know that the `/ios-route-map:values/` should be ignored and that the `ios-route-map:value` should be replaced by a "uint32"?

The simple answer is "you shouldn't"!! The data should conform to the schema definition and the rules laid out by RFC 7951. If we look at the **IOS XE 16.9.1** models and the schema tree for `metric`:

```
$ pyang -f tree Cisco-IOS-XE-native.yang Cisco-IOS-XE-route-map.yang --tree-path=native/route-map/route-map-seq/set/metric
module: Cisco-IOS-XE-native
  +--rw native
     +--rw route-map* [name]
        +--rw ios-route-map:route-map-seq* [ordering-seq]
           +--rw ios-route-map:set
              +--rw ios-route-map:metric
                 +--rw (ios-route-map:metric-choice)?
                    +--:(ios-route-map:relative-value)
                    |  +--rw ios-route-map:metric-change?   string
                    +--:(ios-route-map:absolute-values)
                       +--rw ios-route-map:values
                          +--rw ios-route-map:value?         uint32
                          +--rw ios-route-map:delay?         string
                          +--rw ios-route-map:reliability?   uint8
                          +--rw ios-route-map:loading?       uint8
                          +--rw ios-route-map:MTU?           uint32
```

This definition would see us encode a simple metric thus:

```
"metric": {
  "values": {
    "value": 234
  }
}
```

IOS XE 16.8.1 would, however, expect to see:

```
"metric: "234"
```

I think that you may have been looking at the models for IOS XE 16.9.1, but running against an earlier image. Because the models are evolving fast, there is no guaranteed backwards compatibility between IOS XE version right now. This is something that isn't well enough documented, but we are looking at how we can improve this. Regardless, applications should be using the revision information in the models published by any one release and checking if the models have changed. A tool like pyang can help with this.

Cheers,

Einar

**Comment by briantilburgs** [comment]
Thanks for your help Einar, I do understand the YANG a bit better now and I was able to create the scripts I needed to migrate from REST API to RESTCONF
