### ISSUE TITLE
`yang-viewer` not working

### ISSUE THREAD

**Issue by sjlongland** [YangModels/yang#478]
Hi,
I'm just getting started figuring out YANG with the view of describing the configuration for a small industrial device (which will use CoMI for configuration).  In an effort to better understand what I was writing I tried getting `yang-viewer` working.

Out of the box it fails to find a snapshot, a problem solved by this patch:
```
diff --git a/tools/yang_viewer/pom.xml b/tools/yang_viewer/pom.xml
index 9a3d5a4e..789ae501 100755
--- a/tools/yang_viewer/pom.xml
+++ b/tools/yang_viewer/pom.xml
@@ -11,7 +11,7 @@
        <description>YANG parser</description>
 
        <properties>
-               <odl.yang.version>0.6.2-SNAPSHOT</odl.yang.version>
+               <odl.yang.version>0.6.3-Helium-SR1</odl.yang.version>
                <java.version.source>1.7</java.version.source>
                <java.version.target>1.7</java.version.target>
                <maven.compile.plugin.version>3.2</maven.compile.plugin.version>
@@ -231,4 +231,4 @@
                </repository>
        </repositories>
 
-</project>
\ No newline at end of file
+</project>
```

However, running the tool, it tells me to drag and drop the file.  How does one do that in `xterm`?

**Comment by sjlongland** [comment]
Yeah, I think the assumption that everyone runs a desktop environment is an invalid one.  `xterm` interprets drag as "select text for copying to the clipboard".

If I want to open `foo.odt` on my computer, I do so by running `lowriter foo.odt`… that fires up LibreOffice Writer and tells it to open `foo.odt` in the current working directory.  Alternatively, I launch LibreOffice from my desktop's menu and tell it `File`→`Open`.  From what I've seen, even the Xerox Altos worked this way.  For certain I was not dragging files from File Manager to Word for Windows 6.0 to open my documents 20+ years ago.

Why change this paradigm now?

Anyway, I've moved on from using YANG… was going to look at creating a few models to use with CoMI, but have since come to the realisation that CoMI won't really work for the application we have in mind.  If no one is maintaining this, then I guess we'll just leave it there, might be an idea to remove it from the repository as there's little sense in keeping broken code laying around.

**Comment by einarnn** [comment]
I’ve never been a fan of how `yang_viewer` worked 😉
