### ISSUE TITLE
Install Protocols Should be Identities

### ISSUE THREAD

**Issue by riw777** [YangModels/yang#5]
BGP, EIGRP, and I2RS, at least, should be included in the list. There are a number of other protocols in the MANET space that will eventually need to be added, as well as various other learning mechanisms, so there should be some space for new protocols and installs.

**Comment by aashaikh** [comment]
agreed, we've already made the change to identities to make it easier to add other sources in the future, and we can add other protocols that are in use.

in general, we've tried to stick with things that reflect current operational practice so not sure that I2RS, for example, meets that criteria yet.

**Comment by einarnn** [comment]
Not an issue for this repo as such. Closing!
