### ISSUE TITLE
Be clear about the ietf/DRAFT tree

### ISSUE THREAD

**Issue by evyncke** [YangModels/yang#508]
The README.md at https://github.com/YangModels/yang/tree/master/standard/ietf should be clear tha the DRAFT sub-directory is not up to date

**Comment by miroslavKovacPantheon** [comment]
Good point also we should let them know that ietf-drafts are kept in https://github.com/YangModels/yang/tree/master/experimental/ietf-extracted-YANG-modules directory

________________________________
Od: Eric Vyncke <notifications@github.com>
Odoslané: streda, 28. novembra 2018 15:58:39
Komu: YangModels/yang
Kópia: Subscribed
Predmet: [YangModels/yang] Be clear about the ietf/DRAFT tree (#508)


The README.md at https://github.com/YangModels/yang/tree/master/standard/ietf should be clear tha the DRAFT sub-directory is not up to date

**Comment by einarnn** [comment]
Please submit a PR with suggested updates.

Cheers,

Einar
