### ISSUE TITLE
Remove old OpenDaylight internal config system (CSS) YANG models

### ISSUE THREAD

**Issue by vorburger** [YangModels/yang#554]
Modes such as the [opendaylight-dom-broker-impl.yang](https://github.com/YangModels/yang/blob/master/experimental/odp/opendaylight-dom-broker-impl.yang) describe internal Java object wiring of OpenDaylight internal config system (CSS), and IMHO make no sense to / could never be of any real world interest outside of ODL's internal code...

Further and more importantly, these have long ago disappeared from OpenDaylight (me and others have replaced what this used to be used for by regular Java dependency injection; initially OSGi Blueprint XML and more recently even simpler `@javax.annotation.Inject`).

Would you guys like a PR to [to git rm e.g. all of these](https://github.com/YangModels/yang/search?q=config%3Amodule-type&unscoped_q=config%3Amodule-type) ?

@tnadeau

**Comment by miroslavKovacPantheon** [comment]
I would be ok with removing modules from ODP folder of what you proposed.. but certainly not the yang-catalog@2018-04-03.yang module from ietf-extracted-YANG-modules and Cisco-IOS-XE-wireless-access-point-oper.yang from cisco/xe/16101 folder which are in there included too. but that is probably what you meant anyway. 

But still @tnadeau should have a last word for this and maybe @bclaise and @einarnn might have some opinion on this.

**Comment by bclaise** [comment]
These YANG modules are old. Yes, a cleanup, along with posting the latest YANG modules, would be welcome.

**Comment by vorburger** [comment]
> These YANG modules are old. Yes, a cleanup, 

https://github.com/YangModels/yang/pull/555

> These models are meant to mimic what is used in ODL, so the changes here are intended to reflect whats in the project. Please confirm that the project is ok with these mods and if so, please send a PR.

These have long ago disappeared from OpenDaylight.

> along with posting the latest YANG modules, would be welcome.

https://github.com/YangModels/yang/issues/556
