### ISSUE TITLE
Missing 'aggregate-address' in router bgp

### ISSUE THREAD

**Issue by esmagar** [YangModels/yang#582]
Running the following commands manually in equipment (XE 16.10):
```
router bgp 65001
 aggregate-address 10.90.0.0 255.255.0.0
```

The information appears when executing 'show running-config':
```
router bgp 65001
 bgp log-neighbor-changes
 aggregate-address 10.90.0.0 255.255.0.0
!
```

But executing `get-config` through netconf operation does not return the `aggregate-address` info:
```
...
<router>
	<bgp xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-bgp">
		<id>65001</id>
		<bgp>
			<log-neighbor-changes/>
		</bgp>
	</bgp>
</router>
...
```

**Comment by einarnn** [comment]
@esmagar, the aggregate address command you have used above is a "legacy" command. There are a number of these, that, when configured at thje "global" level of BGP, will not show via netconf/yang or restconf.

However, if your configuration looks like:

```
#sh run | sec router bgp
router bgp 65001
 bgp log-neighbor-changes
 !
 address-family ipv4
  aggregate-address 10.90.0.0 255.255.0.0
 exit-address-family
```

_(Please note that you can just add the `address-family ipv4` to your existing config, and your aggregate address command will magically move to the address family context.)_

Then you should see:

```
$ ncc -g -x /native/router
<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
  <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
    <router>
      <bgp xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-bgp">
        <id>65001</id>
        <bgp>
          <log-neighbor-changes>true</log-neighbor-changes>
        </bgp>
        <address-family>
          <no-vrf>
            <ipv4>
              <af-name>unicast</af-name>
            </ipv4>
          </no-vrf>
        </address-family>
      </bgp>
    </router>
  </native>
</data>
```

Note that this was a deliberate design and implementation choice as the config you entered is considered legacy, and there were challenging technical issues in trying to support both variants of the command. This could be documented better by Cisco, and, as I work for Cisco, I will pass this on.

This isn't an issue that is relevant to this repository, so I'm also closing it.

Cheers,

Einar
