### ISSUE TITLE
Cisco IOS XE multi-line banners not supported

### ISSUE THREAD

**Issue by moffetma** [YangModels/yang#621]
Multi-line banners, especially of the lengthy legal notice type required by many organizations, get truncated and do not display correctly when attempting to configure them via REST

grouping banner-grouping {
      leaf banner {
        description
          "Banner message format, c banner-text c, where 'c' is a delimiting character";
        type string;
      }
    }
    container banner {
      description
        "Define a login banner";
      container exec {
        description
          "Set EXEC process creation banner";
        uses banner-grouping;
      }
      container login {
        description
          "Set login banner";
        uses banner-grouping;
      }
      container prompt-timeout {
        description
          "Set Message for login authentication timeout";
        uses banner-grouping;
      }
      container motd {
        description
          "Set Message of the Day banner";
        uses banner-grouping;
      }
}

**Comment by einarnn** [comment]
@moffetma, please report this as an implementation issue to Cisco TAC if you can. This is not a problem with the model itself.
