### ISSUE TITLE
Missing 'offset-list' in 'router.rip'

### ISSUE THREAD

**Issue by esmagar** [YangModels/yang#648]
Running the following commands in equipment (XE 16.11):
```
router rip
 offset-list 0 out 4 GigabitEthernet3
 network 10.0.0.0
```

`router rip` is stored in the router with the `offset-list` info:
```
router rip
 offset-list 0 out 4 GigabitEthernet3
 network 10.0.0.0
!
```

But `get-config` netconf operation does not return the `offset-list` info:
```xml
<router>
	<rip xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-rip">
		<network>
			<ip>10.0.0.0</ip>
		</network>
	</rip>
</router>
```

**Comment by einarnn** [comment]
@esmagar, suggest you report these issues via your Cisco account team and/or via Cisco TAC, assuming you have a service contract. Cisco makes it models available via GitHub, but they are presented on an is-is basis, and the owners of this repository cannot address missing content.
