### ISSUE TITLE
Missing 'timers' in 'router.rip.address-family'

### ISSUE THREAD

**Issue by esmagar** [YangModels/yang#650]
Running the following commands in equipment (XE 16.11):
```
vrf definition VRF_001
 address-family ipv4

router rip
 network 10.0.0.0
 address-family ipv4 vrf VRF_001
  timers basic 5 15 30 20
```

`router rip` is stored in the router with the `timers` info:
```
router rip
 network 10.0.0.0
 !
 address-family ipv4 vrf VRF_001
  timers basic 5 15 30 20
  no auto-summary
 exit-address-family
!
```

But `get-config` netconf operation does not return the `timers` info:
```xml
<router>
	<rip xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-rip">
		<network>
			<ip>10.0.0.0</ip>
		</network>
		<address-family>
			<ipv4>
				<vrf>
					<name>VRF_001</name>
				</vrf>
			</ipv4>
		</address-family>
	</rip>
</router>
```

**Comment by einarnn** [comment]
@esmagar, suggest you report these issues via your Cisco account team and/or via Cisco TAC, assuming you have a service contract. Cisco makes it models available via GitHub, but they are presented on an is-is basis, and the owners of this repository cannot address missing content.
