### ISSUE TITLE
Missing 'remark' in 'ip.access-list'

### ISSUE THREAD

**Issue by esmagar** [YangModels/yang#651]
Running the following commands in equipment (XE 16.11):

```
ip access-list extended TEST
 remark remarkTest
```

The `ip access-list` configuration is stored in the router with the `remark `info.

But `get-config` netconf operation does not return the `remark `info.

**Comment by einarnn** [comment]
@esmagar, suggest you report these issues via your Cisco account team and/or via Cisco TAC, assuming you have a service contract. Cisco makes it models available via GitHub, but they are presented on an is-is basis, and the owners of this repository cannot address missing content.
