### ISSUE TITLE
Add OpenConfig as submodule

### ISSUE THREAD

**Issue by remingtonc** [YangModels/yang#656]
Given OpenConfig is an operator standards body (working group... semantics?), move that https://github.com/openconfig/public is added as a submodule to `experimental/` or `standard/`. Given the IETF cronjobs, should be relatively easy to keep the submodule up to date in a similar fashion.

`git submodule add https://github.com/openconfig/public standard/openconfig/`

**Comment by bclaise** [comment]
The Openconfig YANG modules were there initially but the OpenConfig people removed them. You have to speak with/convince them.

**Comment by einarnn** [comment]
It would be fine with me, but agree with Benoit that they should do this.

**Comment by einarnn** [comment]
Not an issue for this repo as such. Closing!
