### ISSUE TITLE
IOS-XE Interfaces Statistics - out-octets uint32

### ISSUE THREAD

**Issue by lucabrasi83** [YangModels/yang#657]
Hi,

Is there any specific reason why under the interfaces-oper YANG model / statistics container the `out-octets` is an unsigned int32 type while `in-octets` is an an unsigned int64 ?

[https://github.com/YangModels/yang/blob/master/vendor/cisco/xe/16111/Cisco-IOS-XE-interfaces-oper.yang#L2504](https://github.com/YangModels/yang/blob/master/vendor/cisco/xe/16111/Cisco-IOS-XE-interfaces-oper.yang#L2504)

Thanks

**Comment by einarnn** [comment]
This is probably an oversight. However, this is not an issue for this git repo, it is an issue for Cisco. I shall pass this one, but close this issue. Siggest you may also want to raise this with Cisco TAC and/or your account team if you can.
