### ISSUE TITLE
ietf yang expired drafts

### ISSUE THREAD

**Issue by miroslavKovacPantheon** [YangModels/yang#658]
@einarnn  and @tnadeau 

We are keeping all the ietf draft modules under yang/experimental/ietf-extracted-YANG-modules/ which is exactly what as we want because we want just most recent ietf drafts in there. My question is right now that I would like to add all the expired drafts there as well for a day or two or one week maximum and then use the code we have to get rid of them again. but before we do I would run in yangcatalog a job that would get all the "raw.githubusercontent.com" with a commit hash id instead of saying master which we wrongly did up until now. This caused that old modules return 404 not found from github once they are replaced by new one. And also we would finally have all the ietf modules in yangcatalog.org

just to give you an example this -> https://raw.githubusercontent.com/YangModels/yang/master/experimental/ietf-extracted-YANG-modules/ietf-te-types@2019-02-06.yang does not work any more because it is replaced by this https://raw.githubusercontent.com/YangModels/yang/master/experimental/ietf-extracted-YANG-modules/ietf-te-types@2019-07-05.yang

**Comment by einarnn** [comment]
I see nothing wrong with leaving expired drafts in place for some period of time. But I'm not 100% sure what else you are proposing to do with the "_but before..._" text. Is this just a change to yangcatalog?

**Comment by miroslavKovacPantheon** [comment]
that is the job that would populate the yangcatalog database with all the modules (even expired drafts) and would submit the correct schema (which is link to the yang module and would not use master in it but commit id instead)

**Comment by miroslavKovacPantheon** [comment]
the yang modules were updated and removed. This is not an issue anymore. closing it.
