### ISSUE TITLE
ipv4 ACL remark doesn't work

### ISSUE THREAD

**Issue by davistonegit** [YangModels/yang#667]
**Summary**
IPv4 ACL remark yang model does not work with Cisco IOS-XE. 
For IPv4 ACL, the remark doesn't require a sequence number. However in the yang model, the sequence number is enforced.

**Error message**
Here is error msg that I am seeing from ansible:
"msg": "error editing configuration: expected tag: sequence, got tag: remark"

**Related Yang model**
In the yang model "Cisco-IOS-XE-acl.yang", the "acl-remark-grouping" is placed within "ipv4-std-acl-grouping". 
  grouping ipv4-std-acl-grouping {
    list access-list-seq-rule {
      key "sequence";
      leaf sequence {
        type uint64 {
          range "1..2147483647";
        }
      }
      choice deny-permit {
        container deny {
          description
            "Specify packets to reject";
          uses ipv4-std-ace-grouping;
        }
        container permit {
          description
            "Specify packets to forward";
          uses ipv4-std-ace-grouping;
        }
      }
      uses acl-remark-grouping;
    }
  }

**Comment by einarnn** [comment]
@davistonegit, YANG models on IOS XE do not behave externally in exactly the same way as CLI, and should not be expected to. Note that this includes **not** being able to do everything that may be done via CLI.

When managing ACLs via NETCONF or RESTCONF, a client needs to adhere to the YANG data model. This means that when configuring *inline* remarks, i.e. inside an `access-list-seq-rule`, a sequence number must be used. For example:

```xml
<config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
  <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
    <ip>
      <access-list>
        <extended xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-acl">
          <name>NAME</name>
          <access-list-seq-rule>
            <sequence>10</sequence>
            <remark>foo</remark>
          </access-list-seq-rule>
          <access-list-seq-rule>
            <sequence>15</sequence>
            <ace-rule>
              <action>permit</action>
              <protocol>ip</protocol>
              <any/>
              <dst-any/>
            </ace-rule>
          </access-list-seq-rule>
          <access-list-seq-rule>
            <sequence>20</sequence>
            <remark>bar</remark>
          </access-list-seq-rule>
        </extended>
      </access-list>
    </ip>
  </native>
</config>
```

This data can be retrieved in the same format, but note that when such an ACL provisioned **on a CSR 1000v** via NETCONF is retrieved via the CLI it looks like:

```
csr1kv#sh run | sec ip access-list extended NAME
ip access-list extended NAME
 15 permit ip any any
 10 remark foo
 20 remark bar
```

Hope this explanation helps. However, this issue isn't really one for this GitHub repository as it only provides a location for vendors to publish the models they support. If you have concerns over the behavior of the model, or its correctness, please engage your vendor via their support team.
