### ISSUE TITLE
Can't upload models to Yang Explorer

### ISSUE THREAD

**Issue by Thom9790** [YangModels/yang#699]
Hello there!

After a long week of trials and tribulations, I have finally gotten Yang Explorer to (more or less) work on a Ubuntu 18.04.02 virtual machine. However I cannot upload any models without getting either one or several errors. I get either:
- Bad value "1.1" (should be version)
- module "XXXX" not found in search path
- not defined in the XPath function

I downloaded the models and placed the folders in the same folder as Yang Explorer. 

I've had trouble, since there isn't a single even remotely useful guide on how to set this up. This isn't helped with me being a beginner at Linux. Is there anyone who has a constructive answer to what I have done wrong? For Netconf-Yang being the "Next big thing", there isn't any help to find elsewhere on the net about it. 

Attached is a screenshot of the error I get when trying to upload a module. 

![YangBlows](https://user-images.githubusercontent.com/56293357/66375800-849d6680-e9ae-11e9-8a8b-6b9eed44eb98.PNG)

**Comment by einarnn** [comment]
@Thom9790, this issue tracker is not for Yang Explorer Issues. Suggest you look at https://github.com/CiscoDevNet/yang-explorer. I will close this comment.

**Comment by Thom9790** [comment]
But the only models I can't upload are the ones in this package. The default ones I can upload no problem. That must clearly mean there is a problem here.
