### ISSUE TITLE
Accept and Reject route aren't that simple

### ISSUE THREAD

**Issue by riw777** [YangModels/yang#7]
Reject and accept route aren't that simple. There is a difference between accepting the route into the local database of the routing protocol, and installing it into an actual forwarding table. In a link state protocol, for instance, it is routine to filter routes between the SPT and the routing table they're intended for.

**Comment by plajjan** [comment]
Exactly what YANG model and line are you referring to?
If we are looking at the routing-policy (https://github.com/YangModels/yang/blob/master/experimental/openconfig/policy/routing-policy.yang#L356) I think it is as easy as accept/reject. What else would you expect to be able to express?

Are you referring to some other model?

**Comment by einarnn** [comment]
Too old. Closing.
