### ISSUE TITLE
proto generation fails with cisco yang xr models

### ISSUE THREAD

**Issue by sbezverk** [YangModels/yang#719]
In Cisco yang/vendor/cisco/xr/701/Cisco-IOS-XR-types.yang I hit a couple of errors when I try to generate proto. I use openconfig/ygot generate tool to generate proto file for go lang.

first issue is here:
```
  typedef Char-num {
    type union {
      type string {
        pattern "(0x[0-9A-Fa-f]{1,2}|\\p{IsBasicLatin}|\\p{IsLatin-1Supplement})";
      }
      type uint8;
    }
    description
      "Takes a character or its ASCII decimal equivalent
       (0-255).";
  }
```
```
ERROR Generating Code: ../../yang/vendor/cisco/xr/701/Cisco-IOS-XR-types.yang:396:9: bad pattern: invalid character class range: (0x[0-9A-Fa-f]{1,2}|\p{IsBasicLatin}|\p{IsLatin-1Supplement})
```

And second error is here:
```
  typedef Bgp-ipv4-flowspec-address {
    type string {
      pattern "[a-fA-F0-9]{4096}";
    }
    description
      "An IPV4 Flowspec address in hexadecimal notation.";
  }
```

It seems it is not a valid repeat count, I think 1000 is maximum.

Am I doing something wrong? missing steps or something? Appreciate some ideas.

**Comment by sbezverk** [comment]
I fixed generation by changing :
Line 396:
```
 typedef Char-num {
    type union {
      type string {
        pattern "(0x[0-9A-Fa-f]{1,2})";
      }
      type uint8;
    }
    description
      "Takes a character or its ASCII decimal equivalent
       (0-255).";
  }

  typedef Tty-escape-char-num {
    type union {
      type string {
        pattern "(0x[0-9A-Fa-f]{1,2}|DEFAULT|BREAK|NONE)";
      }
      type uint8;
    }
    description
      "Escape character or its ASCII decimal equivalent
       (0-255) or one of the three string DEFAULT, BREAK,
       NONE.";
  }
```
```
  typedef Bgp-ipv4-flowspec-address {
    type string {
      pattern "[a-fA-F0-9]{1000}";
    }
    description
      "An IPV4 Flowspec address in hexadecimal notation.";
  }

  typedef Bgp-ipv6-flowspec-address {
    type string {
      pattern "[a-fA-F0-9]{1000}";
    }
    description
      "An IPV6 Flowspec address in hexadecimal notation.";
  }

 ```

**Comment by einarnn** [comment]
@sbezverk, there are probably two issues here:

- ygot probably expects POSIX RegEx patterns, but YANG does not use POSIX; it uses regular expressions as defined [here](https://www.w3.org/TR/2004/REC-xmlschema-2-20041028/#regexs)
- RFC 5575 specifies that the BGP flowspec NLRI values can be up to 4095 octets (see [here](https://tools.ietf.org/html/rfc5575#section-4)), so a limit of 1000 is not RFC compliant AFAIK.

So, while your edits may get ygot to compile the models, there is _probably_ no issue with the model, and the ygot-generated code may not reflect the real semantics of the model.

**Comment by einarnn** [comment]
Not an issue for this repo as such. Closing!
