### ISSUE TITLE
Double augments in cisco/xe/16101

### ISSUE THREAD

**Issue by keanujones** [YangModels/yang#722]
There are multiple conflicting augments in the yang files found in/cisco/xe/16101

**Conflicts with augments:**

- In **Cisco-IOS-XE-ethernet** there is this grouping:
```
  grouping config-interface-macsec-grouping {
    leaf  macsec {
      description
        "Enable macsec on the interface";
      type empty;
    }
    container macsec-option {
      description
        "Enable macsec on the interface";
      container macsec {
        leaf dot1q-in-clear {
          description
            "Dot1q in Clear option";
          type enumeration {
            enum "1";
          }
        }
        container replay-protection {
          description
            "Set replay-protection";
          leaf window-size {
            description
              "Set replay window-size";
            type uint32;
          }
        }
      }
    }
  }
```

- In **Cisco-IOS-XE-ethernet** there are these augments:
```
  augment "/ios:native/ios:interface/ios:FastEthernet" {
    uses config-interface-ethernet-grouping;
    uses config-interface-ethernet-member-link-lacp-grouping;
    uses config-interface-macsec-grouping {
      if-feature ios-features:macsec;
    }
  }

  augment "/ios:native/ios:interface/ios:GigabitEthernet" {
    uses config-interface-ethernet-grouping;
    uses config-interface-ethernet-member-link-lacp-grouping;
    uses config-interface-macsec-grouping {
      if-feature ios-features:macsec;
    }
  }

  ...

```

- In **Cisco-IOS-XE-switch** there is this grouping:
```
grouping config-interface-switch-grouping {
	
	...

    // interface * /macsec
    leaf macsec {
      description
        "Enable macsec on the interface";
      type empty;
    }
    container macsec-option {
      description
        "Enable macsec on the interface";
      container macsec {
        container replay-protection {
          description
            "Set replay-protection";
          leaf window-size {
            description
              "Set replay window-size";
            type uint32;
          }
        }
        leaf network-link {
          description
            "Enable macsec on switch connected interface";
          type empty;
        }
      }
    }
  }
```

- In **Cisco-IOS-XE-switch** there are these augments:
```
augment "/ios:native/ios:interface/ios:FastEthernet" {
    uses config-interface-switch-grouping;
    uses ios-dt:config-interface-device-tracking-grouping;
  }

  augment "/ios:native/ios:interface/ios:GigabitEthernet" {
    uses config-interface-switch-grouping;
    uses ios-dt:config-interface-device-tracking-grouping;
  }

...
```

**Conclusion:** there are two different groupings, with two `leafs `and two `containers `with the same name, used to agument the same interfaces. **For example there would be two leafs with name _macsec_ in _/ios:native/ios:interface/ios:GigabitEthernet_**

This has been observed in /cisco/xe/16101 but is also present in other versions of /cisco/xe

I have searched the yang documentation but found no mention of this. Is it an error? If not, any information about the expected result of /ios:native/ios:interface/ios:FastEthernet and /ios:native/ios:interface/ios:GigabitEthernet would also be helpful.

**Comment by einarnn** [comment]
@keanujones, augmentations instantiated in separate YANG modules will actually not conflict technically as they will be ins separate namespaces, extending container and leaf names with the namespace. Also, you must take into account deviations that may be declared for certain platforms that may have an impact.

I’m not saying there isn’t potentially an issue in this area, but there are more considerations. For example, the module a Cisco-IOS-XE-switch is only supported on Catalyst switches, but ISR and ASR routers also support some L2 behaviors.

If you have any observed issues on a device, I’d be interested in hearing more.

**Comment by einarnn** [comment]
Not an issue for this repo as such. Closing!
