### ISSUE TITLE
IOS XR advertises SNMPv2-SMI@1970-01-01, rev not specified in module

### ISSUE THREAD

**Issue by remingtonc** [YangModels/yang#727]
[SNMPv2-SMI@1970-01-01](https://github.com/YangModels/yang/blob/dd11d4f8b19854727f60d329f9f8f837df24b84c/vendor/cisco/xr/701/capabilities-ncs5k.xml#L239) is advertised in `capabilities-ncs5k.xml` but no revision is specified in [SNMPv2-SMI.yang](https://github.com/YangModels/yang/blob/dd11d4f8b19854727f60d329f9f8f837df24b84c/vendor/cisco/xr/701/SNMPv2-SMI.yang#L4) - is there default behavior to default revision to `1970-01-01` or is this a bug?

**Comment by einarnn** [comment]
This is the default value added by the libsmi tools used to create YANG models from SNMP MIBs (according to the algorithm in RFC 6643) when the SNMP MIB has no last revision date. The bug is in effect with the source SNMP MIB.

Cheers,

Einar

**Comment by remingtonc** [comment]
There is no default value in the YANG module - but is advertised in `capabilities*.xml` as having a revision. So there is some kind of mismatch here - `libsmi` is not adding a revision to the model, yet we advertise a revision, so is the tooling generating `capabilities*.xml` the one adding a default revision, and the default behavior in YANG tooling be to add imply revision `1970-01-01` to any un-rev'd module, or is the `libsmi` tooling at fault?

**Comment by einarnn** [comment]
Given the date, I would say that IOS XR is just zero-initializing the revision date when advertising. If there is no revision date in the YANG module, this is probably a reasonable choice to make. And, AFAIK, advertising the revision is mandatory. As is having a revision in a module.

The libsmi tooling is/was at fault. I asked for that to be fixed a few years ago, and I think it was, but if vendors don't use it, then it won't help.

**Comment by remingtonc** [comment]
Are there any other colloquial defaults that you are aware of? Issue may be considered closed, thank you.
