### ISSUE TITLE
pyang report a error ,what is wrong ? anyone know this problem ?

### ISSUE THREAD

**Issue by zhanggongc** [YangModels/yang#777]
root@debian:/home/cailei/openconfig/public/release/models/acl# 
root@debian:/home/cailei/openconfig/public/release/models/acl# pyang --plugindir $PYBINDPLUGIN -f pybind -o openconfig_acl.py openconfig-acl.yang
no format specified
root@debian:/home/cailei/openconfig/public/release/models/acl# 
root@debian:/home/cailei/openconfig/public/release/models/acl# 
"no format specified"   why  ?

![image](https://user-images.githubusercontent.com/58503468/74710408-8cbeba00-525c-11ea-98b4-46d436aca185.png)

**Comment by einarnn** [comment]
Please visit:

https://github.com/mbj4668/pyang

...and raise the issue there. Closing this one.
