### ISSUE TITLE
Question: Is it possible to have yang data tree without root container?

### ISSUE THREAD

**Issue by maksimvuleta** [YangModels/yang#804]
Is it possible that YANG starts with the list as a root, not with the container?

For example like this:
module example-module {
  namespace "example-module";
  prefix exm;
  list example-module-list {
    key "index";
    leaf index {
      type uint32;
    description
      "Index.";
    }
....
}

If it is possible, how to represent it in the xml?

**Comment by miroslavKovacPantheon** [comment]
hello,

yes this is possible. It s a good practice to have always root container and also have just one root container. but root list is fine as well. but I would not recommend two root nodes or more of them although that is possible as well

I recommend watching this https://www.youtube.com/watch?v=23iu0RWZ0UE&t=2248s
move to minute 32

**Comment by einarnn** [comment]
Agree with @miroslavKovacPantheon here, but this isn’t an issue with this repository, so closing this issue 🙂
