### ISSUE TITLE
syntax issues in experimental/ietf-extracted-YANG-modules/ files

### ISSUE THREAD

**Issue by jluhrsen** [YangModels/yang#806]
What is the proper way to resolve some syntax errors in the files in that folder?

Can I just submit a PR with the changes?

Thanks

**Comment by miroslavKovacPantheon** [comment]
Hello,

These are the ietf modules that come from IETF draft documents and there is probably a specific process that needs to followed or some website that keeps track of the bugs for these modules maybe. I myself would look for the contact information of the yang and try to contact WG email list of that specific module or some person if there is no WG email. For example module acl-ip has this:

```
contact
         "WG Web: http://tools.ietf.org/wg/netmod/
        WG List: netmod@ietf.org
        WG Chair: David Kessens
        david.kessens@nsn.com
        WG Chair: Juergen Schoenwaelder
        j.schoenwaelder@jacobs-university.de
        Editor: Lisa Huang
        yihuan@cisco.com
        Editor: Alexander Clemm
        alex@cisco.com
        Editor: Andy Bierman
        andy@yumaworks.com";
```

I believe @bclaise could give you even more proper answer for this.

**Comment by tnadeau** [comment]
Hi Jamo,

Yes, just ensure it passes the CI tests (or you correct them) before pushing the PR.

—Tom

**Comment by miroslavKovacPantheon** [comment]
@tnadeau, @bclaise, @einarnn, @jluhrsen, @evyncke

I tried to put everyone that has something to do with this.

So It s not that simple.. since this is automatically populated folder of IETF draft modules his changed would be replaced next day that it was merged. Yangcatalog is checking all the new drafts on daily basis and if there is anything that does not match what s in the draft it will be replaced by that. This is done automatically as you can see all the modules here are added by the same person with the same commit message.

This is why I suggested to do changes correctly and ask for attention from the module creators. If they update a draft our tool will pick it up and the change will be populated to this repository as well.

Thank you
Miroslav Kovac

**Comment by tnadeau** [comment]
That is a good idea. We had this issue about a year ago when there was another mass update of the folders.

—Tom

**Comment by jluhrsen** [comment]
Thanks for the replies,

(Hi Tom) :)

The reason I was asking here is that, in OpenDaylight, we have some automated tests that run a
yang validator and we are pulling this repo to test it against. It will fail (properly) against all of these
files that have improper syntax.

I'm counting 15 different places I'll have to reach out to see how to get things fixed, but that might
be too cumbersome for me at this point. Even if I did find a way to get them resolved, and get our
ODL automation to pass, nothing would stop more invalid yang files from making it in on the next
merge.

Are the files in the experimental folder just a playground and not really a big deal if they won't parse?

**Comment by einarnn** [comment]
@jluhrsen, the intent of the experimental files is to provide regular, automated access to in-progress models and to provide feedback such as yours to authors about quality and usefulness of the models. Theses models are not normative, and, as such, it’s not a big deal if they fail to parse. The authors should be notified, though, that their drafts contain errors.

**Comment by tnadeau** [comment]
> On Mar 31, 2020, at 7:18 PM, Jamo Luhrsen <notifications@github.com> wrote:
> 
> 
> Thanks for the replies,
> 
> (Hi Tom) :)
> 
> 

Right back at ya!
> The reason I was asking here is that, in OpenDaylight, we have some automated tests that run a
> yang validator and we are pulling this repo to test it against. It will fail (properly) against all of these
> files that have improper syntax.
> 
> I'm counting 15 different places I'll have to reach out to see how to get things fixed, but that might
> be too cumbersome for me at this point. Even if I did find a way to get them resolved, and get our
> ODL automation to pass, nothing would stop more invalid yang files from making it in on the next
> merge.
> 
> Are the files in the experimental folder just a playground and not really a big deal if they won't parse?
> 
> 

I hear you for sure. This is an issue I’ve long since stopped trying to solve. The simplest
solution would be for ODL to *only reference* models that are stored here, and we tried
doing that but as you can see, the cats that were herded previously have gotten away
again.   With this in mind, can you move all of the models, even per version/release, 
here somehow?  We are happy to accommodate sorting them, or tagging, or whatever
is needed.

—Tom

**Comment by jluhrsen** [comment]
Thanks everyone for the replies and helping me understand what is going on.

I have updated our ODL test suites now and will still use this repo to test against, but will
freeze it at a certain commit and manually 'rm -rf' all the trouble. Hopefully I can periodically
update things and move the freeze point up, but I'm guessing there will be something new
broken every time I try. We'll see.

I notice this repo has a number (653) of forks already (guessing others are forking and fixing, but
not sure). I forked it and applied the few changes I was working on before realizing it wouldn't help.
https://github.com/jluhrsen/yang/commit/808ce000e70a3bd440160d33ebcb7b51898d0931
The commit message has a section where I pulled the contact emails from each file I modified
in case someone wanted to try to herd those cats :)

Tom, you asked if we could move all of our models here. I think we had an intern project that
was working on that, but looks like maybe it didn't result in anything. I'll ask about that and see
if anything can be done.

Thanks again everyone,
JamO

**Comment by tnadeau** [comment]
> On Apr 3, 2020, at 12:31 PM, Jamo Luhrsen <notifications@github.com> wrote:
> 
> 
> Thanks everyone for the replies and helping me understand what is going on.
> 
> I have updated our ODL test suites now and will still use this repo to test against, but will
> freeze it at a certain commit and manually 'rm -rf' all the trouble. Hopefully I can periodically
> update things and move the freeze point up, but I'm guessing there will be something new
> broken every time I try. We'll see.
> 
> I notice this repo has a number (653) of forks already (guessing others are forking and fixing, but
> not sure). I forked it and applied the few changes I was working on before realizing it wouldn't help.
> jluhrsen@808ce00 <https://github.com/jluhrsen/yang/commit/808ce000e70a3bd440160d33ebcb7b51898d0931>
> The commit message has a section where I pulled the contact emails from each file I modified
> in case someone wanted to try to herd those cats :)
> 
> Tom, you asked if we could move all of our models here. I think we had an intern project that
> was working on that, but looks like maybe it didn't result in anything. I'll ask about that and see
> if anything can be done.
> 
> 
Cool. Glad to help if you can herd the cats on that one. I just don’t have a ton of time but can help out.

—Tom
