### ISSUE TITLE
Many modules missing Cisco-IOS-XE-*

### ISSUE THREAD

**Issue by xcdr** [YangModels/yang#829]
I want to display tree for Cisco-IOS-XE-nat.yang and have problem with missing types:

```
15:40 $ pyang -f tree vendor/cisco/xe/1693/Cisco-IOS-XE-nat.yang 
vendor/cisco/xe/1693/Cisco-IOS-XE-nat.yang:10: error: module "Cisco-IOS-XE-types" not found in search path
vendor/cisco/xe/1693/Cisco-IOS-XE-nat.yang:14: error: module "Cisco-IOS-XE-native" not found in search path
vendor/cisco/xe/1693/Cisco-IOS-XE-nat.yang:18: error: module "Cisco-IOS-XE-interface-common" not found in search path
```

For another model with similar types Cisco-IOS-XE-native.yang all works fine.

My pipenv:
```
15:40 $ pip list
Package    Version
---------- -------
lxml       4.5.1  
pip        20.0.2 
pyang      2.2.1  
setuptools 46.1.3 
wheel      0.34.2 
```
Can You help me?

**Comment by einarnn** [comment]
This isn't a workaround, this is the way YANG is defined to work. `pyang` is a compiler, and, as such, needs to know where to find files. It will not automatically add the directory where the file you are compiling/processing is located. It only assumes that files distributed as part of its installation, in the current working directory or added to the path are accessible during compilation.

You also said above that:

> For another model with similar types Cisco-IOS-XE-native.yang all works fine.

This is not what I observe. Any other model that has an import or an include of any other non-standard model will show the same types of errors.

As this isn't a problem with the models distributed or with repo, closing the issue.
