### ISSUE TITLE
Yang Syntax Related Query

### ISSUE THREAD

**Issue by PathakMihir** [YangModels/yang#833]
While working with Yang files,this kind of structure was there in some of the yang file. Want to confirm is this a valid structure.

 list  netconf_server {
                
                        key "local_address";

                        leaf local_address{
                            type string
                        }
                        container netconf_server{
                            leaf id
                        }
                }

In the above structure ,there is container inside the list with the same name .Is this structure valid with the same name?

**Comment by einarnn** [comment]
Yes, this is valid in YANG, but may look a little confusing.

**Comment by einarnn** [comment]
Not an issue for this repo as such. Closing!
