### ISSUE TITLE
Cisco XR Qos model improvement : add class-name as a key

### ISSUE THREAD

**Issue by Tristou27** [YangModels/yang#839]
Hi there,

Would it be possible to add the leaf "class-name" as a key under Cisco XR qos models ? This value is often accessible under "class-stats" and then it should be great to have this leaf as a key as well.

I think for instance to Cisco-IOS-XR-qos-ma-oper which can be classified by service-policies (service-policy-name is a key) but there is no key for class-name.  This could be really useful.

Thanks in advance,

Rgds
Tristan

**Comment by einarnn** [comment]
@Tristou27, I've passed this on to the Cisco engineering team. I suggest that if you work with a Cisco account team you also push for this with your account team.

Cheers,

Einar
