### ISSUE TITLE
Neighbor Set Ambiguity

### ISSUE THREAD

**Issue by riw777** [YangModels/yang#9]
Neighbor set apparently means "the set of neighbors from whom you've learned this route." This isn't a valid set for a link state protocol. For BGP it's useful, and for RIP/EIGRP it overlaps with the forwarding set. This needs to be addressed in some way, probably my marking this as explicitly optional for any given route, or describing it more fully.

Or does the "neighbor set," mean the set of neighbors for whom this filter applies?

**Comment by robshakir** [comment]
Hi - please can you explain what you mean by "making this optional for any given route"? This is not a set that is attached to any RIB entry (assuming that you are referring to the openconfig/policy/routing-policy.yang neighbour set) - but rather one that can be used to perform a match within a certain routing policy. 

The semantics when applied to RIP/EIGRP may need to be examined - since this was expanded in the current revision to be a generic policy model, rather than BGP-specific, some of the wording of the descriptions may need to be cleaned up too.

**Comment by riw777** [comment]
If this is for filtering routes, then we need to consider a couple of things. First, it doesn't make sense to filter routes in a link state protocol based on the neighbor you're receiving the route from. As link state protocols flood, rather than advertise in a "somewhat linear" chain (tongue in a cheek a little here), there's no way to attach any significance to the neighbor you're receiving the route from. It could change each time there's a new flood simply because of timing, with no significance attached. For distance-vector (RIP/EIGRP), it does matter where you're receiving the route from, as this actually impacts who you will forward traffic through for that specific destination. 

It might be "more generic," perhaps (this is just an idea) to consider this a filter based on who you would like, locally, to forward traffic to for a specific given reachable destination. Doing this would allow you, in a link state protocol, to look at the next hop for the route, and for a distance-vector protocol, to act like this is a set of neighbors you'll reject the route from (?). This might be a cleaner and simpler construction than getting into all the differences/etc. between the two different types of protocols.

Or maybe not... It might also be hard for folks to understand this type of construction. Hard to tell.

**Comment by aashaikh** [comment]
if neighbor-set is only useful in the context of BGP, then we can consider moving it to the bgp-policy model, i.e., not have it be part of the generic routing sets.  

of course if someone defines a policy with a neighbor-set match and uses it an import/export policy for a link-state protocol, it should be an error.   we discussed requiring policies to be tagged with the protocol in which they are being used, but ultimately decided that the model complexity was not worth the cost of doing some simple validation.

**Comment by riw777** [comment]
IMHO, this could just be listed as the next hop for the route, and not a neighbor. In the case of a link state protocol, this would be the actual next hop, and not be in reference to a neighbor at all. In the case of a distance vector or path vector protocol, it would be (in most cases, except third party next hop), the peer you received the route you received the route from as well. Just disconnecting the idea of the next hop and the neighbor is what I think needs to be done here.

**Comment by einarnn** [comment]
Too old. Closing.
