### ISSUE TITLE
ietf-hardware yang module failed to install

### ISSUE THREAD

**Issue by Bijendra0508** [YangModels/yang#930]
Hello team,

I was trying to install o-ran-mplane yang module (which has dependency on ietf-hardware yang module) using below commands as a result o-ran-mplane yang installation failed with following erros.

> root@embedded-PC:~# sysrepoctl --verbosity 3 --apply --install o-ran-mplane-int.yang -s ~/
> [INF]: Applying scheduled changes.
> [INF]: No scheduled changes.
> [WRN]: Module's revisions are not unique (2018-06-28).
> [ERR]: Invalid keyword "ianahw:sensor".
> [ERR]: Module "ietf-hardware" parsing failed.
> [ERR]: Importing "ietf-hardware" module into "o-ran-interfaces" failed.
> [ERR]: Module "o-ran-interfaces" parsing failed.
> [ERR]: Importing "o-ran-interfaces" module into "o-ran-mplane-int" failed.
> [ERR]: Module "o-ran-mplane-int" parsing failed.
> sysrepoctl error: Failed to install module "o-ran-mplane-int.yang" (libyang error)

Looking at logs it seems to me that there is some problem in ietf-hardware.yang module which i got from  [here](https://github.com/YangModels/yang/blob/master/standard/ietf/RFC/ietf-hardware%402018-03-13.yang#L1006)

Please let me know how can i fix it. more details are posted on [here](https://github.com/CESNET/netopeer2/issues/787)

**Comment by einarnn** [comment]
@Bijendra0508 , the YANG module `ietf-hardware.yang` parses fine for me with `pyang`:

```

**Comment by einarnn** [comment]
No further dialog for quite a while. Closing.
