### ISSUE TITLE
/rt:routing/rt:ribs/rt:rib/rt:routes/rt:route，Why does this list have no key field？ How to establish a mapping relationship with the parent table when querying the child table of next-hop？

### ISSUE THREAD

**Issue by lanzhu20210114** [YangModels/yang#937]
/rt:routing/rt:ribs/rt:rib/rt:routes/rt:route
Why does this list have no key field？
 How to establish a mapping relationship with the parent table when querying the child container next-hop？

**Comment by einarnn** [comment]
Would be better to follow up with the IETF or other group that authored this model.
