### ISSUE TITLE
What happened with openconfig-bgp.yang support ?

### ISSUE THREAD

**Issue by martinmirko** [YangModels/yang#977]
Hi guys,

I was using this on 6.3.3. and now i have new NCS5501-SE with version 7.1.2 and this is not working anymore. I have blank answer to my requests. I don;t this openconfig-bgp.yang files on the repo anymore. Does it still support openconfig ? What is the replacement ? I can see it dough using YANG Explorer, but it is not working.

This is my NETCONF CALL

<bgp:bgp xmlns:bgp="http://openconfig.net/yang/bgp">
     <bgp:global>
      <bgp:state>
       <bgp:as/>
       <bgp:router-id/>
       <bgp:total-paths/>
       <bgp:total-prefixes/>
      </bgp:state>
     </bgp:global>
     <bgp:neighbors>
      <bgp:neighbor>
       <bgp:neighbor-address/>
       <bgp:state>
        <bgp:session-state/>
       </bgp:state>
       <bgp:afi-safis>
        <bgp:afi-safi>
         <bgp:afi-safi-name xmlns:idx="http://openconfig.net/yang/bgp-types">idx:L3VPN_IPV4_UNICAST</bgp:afi-safi-name>
         <bgp:state>
          <bgp:active>true</bgp:active>
         </bgp:state> 
    	</bgp:afi-safi>
       </bgp:afi-safis>
      </bgp:neighbor>
     </bgp:neighbors>
    </bgp:bgp>
    """

**Comment by einarnn** [comment]
Yes, IOS XR still supports the openconfig models. However, in IOS XR 6.4.1 the routing models moved to under the network instance model. Please explore the `network-instances` subtree. You will find BGP config & state there. See:

> https://github.com/openconfig/public/blob/master/release/models/network-instance/openconfig-network-instance.yang#L731-L740

And to look at the tree:

```
$ pyang -f tree openconfig-network-instance.yang --tree-path=network-instances/network-instance/protocols --tree-depth=5
module: openconfig-network-instance
  +--rw network-instances
     +--rw network-instance* [name]
        +--rw protocols
           +--rw protocol* [identifier name]
              +--rw identifier          -> ../config/identifier
              +--rw name                -> ../config/name
              +--rw config
              |     ...
              +--ro state
              |     ...
              +--rw static-routes
              |     ...
              +--rw local-aggregates
              |     ...
              +--rw bgp
              |     ...
              +--rw isis
                    ...
```

Hope this helps. However, this query isn't an issue for this repository, so closing.
